language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r etc/requirements-test.txt
  - pip install -e .

script:
  - pytest --cov=caelus

after_success:
  - coveralls

branches:
  only:
    - master
