language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r etc/requirements-test.txt
  - pip install .

script:
  - pytest --cov=caelus --cov-report term-missing

after_success:
  - coveralls

branches:
  only:
    - master
