# CI script for windows testing

environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build: off

install:
  # update path to use installed pip
  - set PATH=%PYTHON%\\scripts;%PATH%
  - "pip install -r etc\\requirements-test.txt"
  - "pip install -e ."

test_script:
  - py.test
