# -*- mode: yaml -*-

# Default Caelus Python Configuration

caelus:
  logging:
    log_to_file: True
    log_file: null

    pylogger_options:
      version: 1
      disable_existing_loggers: False

      formatters:
        stdout:
          format: "%(levelname)s: %(message)s"

        default:
          format: "%(asctime)s:%(name)s:%(levelname)s: %(message)s"

      handlers:
        console:
          class: logging.StreamHandler
          level: INFO
          formatter: stdout
          stream: "ext://sys.stdout"

        log_file:
          class: logging.handlers.RotatingFileHandler
          level: DEBUG
          formatter: default
          maxBytes: 10485760
          backupCount: 10
          encoding: utf8

      loggers:
        caelus:
          level: DEBUG
          handlers: [console]
          propagate: no

      root:
        level: DEBUG
        handlers: [console]

  # Configuration for Caelus CML
  caelus_cml:
    # Pick the latest version of CML available
    default: latest

    # Available versions must be provided in configuration files
    versions: []
